name: Build
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt-get install -y clang cmake ninja-build

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build project in release state
        run: |
          mkdir -p build && cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          ninja

  macOS:
    runs-on: macos-12
    steps:
      - name: Install packages
        run: |
          brew install cmake ninja

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build project in release state
        run: |
          mkdir -p build && cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          ninja
