name: Build
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project on Ubuntu
        run: |
          mkdir -p build && cd build
          cmake ..
          make

  MacOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build project on MacOS
        run: |
          mkdir -p build && cd build
          cmake ..
          make
