name: build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  Build-on-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build project on Ubuntu
        run: |
          mkdir -p build && cd build
          cmake ..
          make

  Build-on-MacOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Build project on MacOS
        run: |
          mkdir -p build && cd build
          cmake ..
          make
