name: Build & Tests
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - build-type: Release
            cmake-options: -DBUILD_TESTS=OFF
          - build-type: Debug
            cmake-options: -DBUILD_TESTS=ON

    steps:
      - name: Install packages
        run: |
          sudo apt-get install -y clang cmake ninja-build

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build project in release state
        env:
          BUILD_TYPE: ${{ matrix.build-type }}
          CMAKE_OPTIONS: ${{ matrix.cmake-options }}
        run: |
          mkdir -p build && cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ $CMAKE_OPTIONS
          time ninja

      - name: Run tests
        if: ${{ matrix.build-type == 'Debug' }}
        run: |
          ./build/tests/tests

  macOS:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        include:
          - build-type: Release
            cmake-options: -DBUILD_TESTS=OFF
          - build-type: Debug
            cmake-options: -DBUILD_TESTS=ON

    steps:
      - name: Install packages
        run: |
          brew install ninja

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build project in release state
        env:
          BUILD_TYPE: ${{ matrix.build-type }}
          CMAKE_OPTIONS: ${{ matrix.cmake-options }}
        run: |
          mkdir -p build && cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ $CMAKE_OPTIONS
          time ninja

      - name: Run tests
        if: ${{ matrix.build-type == 'Debug' }}
        run: |
          ./build/tests/tests
